version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - echo Logging in to AWS CodeArtifact...
      - CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain nextwork --domain-owner 816351728413 --region us-west-2 --query authorizationToken --output text`
      - export CODEARTIFACT_AUTH_TOKEN
  build:
    commands:
      - echo "====== TEST PHASE ======"
      - chmod +x run-tests.sh
      - ./run-tests.sh
      - echo "====== BUILD PHASE ======"
      - mvn -s settings.xml compile
      - mvn -s settings.xml package
  post_build:
    commands:
      - echo "Preparing deployment ZIP for CodeDeploy..."
      # create a temporary folder for packaging
      - mkdir -p deploy_package
      - cp target/nextwork-web-project.war deploy_package/
      - cp appspec.yml deploy_package/
      - cp -r scripts deploy_package/
      # zip the contents at root of archive
      - cd deploy_package
      - zip -r ../nextwork-deploy.zip *
      - cd ..
      - echo "Deployment ZIP created:"
      - ls -la nextwork-deploy.zip
      # upload to S3
      - aws s3 cp nextwork-deploy.zip s3://nextwork-devops-cicd-christine/teacup/nextwork-deploy.zip

artifacts:
  files:
    - nextwork-deploy.zip